django/library/core/urls.py
from django.contrib import admin
from django.urls import path

from catalog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.main, name='main'),
    
    path('authors', views.authors, name='authors_catalog'),
    path('authors/<str:name>', views.author, name='author'),
    
    path('publishers', views.publishers, name='publishers_catalog'),
    path('publishers/<str:name>', views.publisher, name='publisher'),
    
    path('add_book', views.add_book, name='add_book'),
    
    path('register', views.register, name='user_register'),
    path('login', views.login, name='user_login'),
    path('logout', views.logout, name='user_logout'),
]

django/library/catalog/models.py
from django.db import models
from transliterate import translit

from functools import cached_property


class Author(models.Model):
    class Meta:
        db_table = 'authors'
    
    last_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    
    @cached_property
    def url(self) -> str:
        return translit(self.last_name, 'ru', reversed=True).lower()
    
    def __repr__(self):
        return f'{self.first_name} {self.last_name}'
    
    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Book(models.Model):
    class Meta:
        db_table = 'books'
    
    title = models.CharField(
        verbose_name='Название', 
        max_length=100
    )
    author = models.ForeignKey(
        Author, 
        verbose_name='Автор', 
        on_delete=models.CASCADE
    )
    
    def __repr__(self):
        return self.title


class Publisher(models.Model):
    class Meta:
        db_table = 'publishers'
    
    id = models.SmallAutoField(primary_key=True)
    name = models.CharField(
        verbose_name='Наименование', 
        max_length=150, 
        unique=True,
        error_messages={
            'unique': 'такое издательство уже существует'
        }
    )
    authors = models.ManyToManyField(Author)
    books = models.ManyToManyField(Book)
    
    @cached_property
    def url(self) -> str:
        return translit(self.name, 'ru', reversed=True).lower()
    
    def __repr__(self):
        return self.name

django/library/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from re import compile

from catalog.models import Author, Publisher, Book


pat_name = compile(r'(?P<name>[A-Za-zА-ЯЁа-яё]{2,})(-(?P=name))?')


def validate_name(value: str):
    if not pat_name.fullmatch(value):
        raise ValidationError(
            f'{value!r} не является именем',
            params={"value": value}
        )


class AddAuthorForm(forms.Form):
    last_name = forms.CharField(
        label='Фамилия',
        max_length=30,
        validators=[validate_name],
    )
    first_name = forms.CharField(
        label='Имя',
        max_length=30,
        validators=[validate_name],
    )
    
    def is_valid(self):
        is_valid = super().is_valid()
        if is_valid:
            if Author.objects.filter(**self.cleaned_data):
                self.add_error(None, 'такой автор уже существует')
                return False
        return is_valid


class AddPublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ['name']


class AddExistingBookToPublisherForm(forms.Form):
    book_id = forms.ChoiceField(
        label='Существующая книга',
        choices= {'': ''} | {
            book.id: repr(book)
            for book in Book.objects.order_by('title')
        },
    )


class AddNewBookToPublisherForm(AddAuthorForm):
    title = forms.CharField(
        label='Название',
        max_length=100,
    )
    
    field_order = ['title', 'last_name', 'first_name']
    
    def is_valid(self):
        # return super(self.__class__.__mro__[1], self).is_valid()
        return super(AddAuthorForm, self).is_valid()

django/library/catalog/views.py
from django.shortcuts import render, redirect
from transliterate import translit

from catalog.forms import (
    AddAuthorForm, 
    AddPublisherForm, 
    AddExistingBookToPublisherForm, 
    AddNewBookToPublisherForm
)
from catalog.models import Author, Publisher, Book

from django.contrib.auth import (
    authenticate, 
    login as auth_login,
    logout as auth_logout,
)
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


authors_cache = {
    translit(author.last_name, 'ru', reversed=True).lower(): author
    for author in Author.objects.order_by('last_name', 'first_name')
}
publishers_cache = {
    translit(pub.name, 'ru', reversed=True).lower(): pub
    for pub in Publisher.objects.order_by('name')
}


def main(request):
    return render(
        request,
        'main.html',
    )


def authors(request):
    if request.method == 'GET':
        form = AddAuthorForm()
    
    elif request.method == 'POST':
        form = AddAuthorForm(request.POST)
        if form.is_valid():
            Author(**form.cleaned_data).save()
        # breakpoint()
    
    return render(
        request,
        'authors.html',
        {
            'authors': Author.objects.order_by('last_name', 'first_name'),
            'form': form,
        }
    )


def author(request, name: str):
    author = authors_cache[name]
    return render(
        request, 
        'author.html',
        {
            'author': author,
            'books': author.book_set.all(),
        }
    )


def publishers(request):
    if request.method == 'GET':
        form = AddPublisherForm()
    
    elif request.method == 'POST':
        form = AddPublisherForm(request.POST)
        if form.is_valid():
            form.save()
            form = AddPublisherForm()
    
    return render(
        request,
        'publishers.html',
        {
            'pubs': Publisher.objects.order_by('name'),
            'form': form,
        }
    )


def publisher(request, name: str):
    pub = publishers_cache[name]
    
    form1 = AddExistingBookToPublisherForm()
    form2 = AddNewBookToPublisherForm()
    
    if request.method == 'POST':
        if request.POST['form'] == 'existing':
            form1 = AddExistingBookToPublisherForm(request.POST)
            form1.full_clean()
            book = Book.objects.get(pk=form1.cleaned_data['book_id'])
            pub.books.add(book)
            form1 = AddExistingBookToPublisherForm()
        
        elif request.POST['form'] == 'new':
            form2 = AddNewBookToPublisherForm(request.POST)
            if form2.is_valid():
                # дописать самостоятельно создание/получение экземпляров автора и книги
                author = ...
                book = ...
                
                pub.books.add(book)
                form2 = AddNewBookToPublisherForm()
    
    return render(
        request,
        'publisher.html',
        {
            'pub': pub,
            'books': pub.books.all(),
            'form1': form1,
            'form2': form2,
        }
    )


def add_book(request):
    context = {
        'added': False,
        'authors': Author.objects.all(),
        'double': False,
    }
    
    if request.method == 'POST':
        # print(request.POST)
        title = request.POST['title']
        author_id = int(request.POST['author_id'])
        double = Book.objects.filter(title=title, author_id=author_id)
        # print(double)
        if not double:
            Book(title=title, author_id=author_id).save()
            context['added'] = True
        else:
            context['double'] = True
    
    return render(
        request,
        'add_book.html',
        context
    )


def register(request):
    if request.method == 'GET':
        form = UserCreationForm()
    
    elif request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main', permanent=True)
    
    return render(
        request,
        'register.html',
        {'form': form}
    )


def login(request):
    if request.method == 'GET':
        form = AuthenticationForm()
    
    elif request.method == 'POST':
        # breakpoint()
        
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('main', permanent=True)
        
        # user = authenticate(
        #     request,
        #     username=request.POST['username'],
        #     password=request.POST['password'],
        # )
        # auth_login(request, user)
        # return redirect('main', permanent=True)
    
    
    return render(
        request,
        'login.html',
        {'form': form}
    )


def logout(request):
    auth_logout(request)
    return redirect('main', permanent=True)

django/library/templates/add_book.html
{% extends 'base.html' %}


{% block content %}
  <br>
  <div>
    {% if added %}
      <h6>Данные добавлены успешно</h6>
    {% endif %}
  </div>
  <br>
  <div>
    <form action="" method="post">
      {% csrf_token %}
      <table cellpadding=5>
        <tr>
          <th align="right">
            <label for="id_title">Название:</label>
          </th>
          <td>
            <input type="text" name="title" id="id_title" required>
          </td>
        </tr>
        <tr>
          <th align="right">
            <label for="id_author">Автор:</label>
          </th>
          <td>
            <select name="author_id" id="id_author" required>
              <option disabled selected></option>
              {% for author in authors %}
                <option value="{{ author.id }}">{{ author }}</option>
              {% endfor %}
            </select>
          </td>
        </tr>
        <tr>
          <td colspan=2 align="center">
            <input type="submit" value="Добавить">
          </td>
        </tr>
      </table>
    </form>
  </div>
  {% if double %}
    <br>
    <div>
      <em>данная книга уже есть в базе</em>
    </div>
  {% endif %}
{% endblock content %}

django/library/templates/author.html
{% extends 'base.html' %}


{% block title %}
  {{ author }}
{% endblock title %}


{% block content %}
  <h2>{{ author }}</h2>
  <div align="left">
    <table cellpadding=15>
      {% for book in books %}
        <tr><td>{{ book.title }}</td></tr>
      {% endfor %}
    </table>
  </div>
{% endblock content %}

django/library/templates/authors.html
{% extends 'base.html' %}


{% block title %}
  Каталог авторов
{% endblock title %}


{% block content %}
  <div align="left">
    <table cellpadding=20>
      {% for author in authors %}
        <tr>
          <td>
            <a href="{% url 'author' author.url %}">{{ author }}</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div>
    <hr>
  </div>
  <div>
    <form action="" method="post">
      {% csrf_token %}
      
      <table cellpadding=5>
        {{ form.as_table }}
      </table>
      
      <input type="submit" value="Добавить">
    </form>
  </div>
{% endblock content %}

django/library/templates/base.html
<!DOCTYPE html>
<!-- базовый шаблон -->
<html>
  <head>
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <style>
      .menu {
        background-color: #D5D595;
        font-size: 16pt;
      }
    </style>
    {% block extra_head %}
    {% endblock extra_head %}
  </head>
  <body>
    {% block header %}
      <div class="menu" align="center">
        {% include 'menu.html' %}
      </div>
    {% endblock header %}
    <div align="center">
      {% block content %}
        <h1>Интернет-каталог библиотеки №7 им. Чернышевского</h1>
      {% endblock content %}
    </div>
    <div align="center">
      {% block extra_content %}
      {% endblock extra_content %}
    </div>
  </body>
</html>

django/library/templates/books.html
{% extends 'base.html' %}


{% block content %}
  <h2>
    {% block heading %}
    {% endblock heading %}
  </h2>
  <div align="left">
    <table cellpadding=15>
      {% for book in books %}
        <tr><td>{{ book.title }}</td></tr>
      {% endfor %}
    </table>
  </div>
{% endblock content %}

django/library/templates/login.html
{% extends 'base.html' %}


{% block title %}
  Вход
{% endblock title %}


{% block header %}
{% endblock header %}


{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    
    <table cellpadding=10>
      {{ form.as_table }}
      <tr>
        <td colspan=2 align="center">
          <input type="submit" value="Войти">
        </td>
      </tr>
    </table>
    
  </form>
{% endblock content %}

django/library/templates/main.html
{% extends 'base.html' %}


{% block title %}
  Главная
{% endblock title %}


{% block content %}
  <h2>Добро пожаловать в интернет-каталог библиотеки №7 им. Чернышевского</h2>
  <table cellpadding=30>
    <tr>
      <td><a href="{% url 'authors_catalog' %}">Авторы</a></td>
      <td><a href="{% url 'publishers_catalog' %}">Издательства</a></td>
    </tr>
  </table>
{% endblock content %}

django/library/templates/menu.html
<table cellpadding=40>
  <tr>
    <td><a href="{% url 'main' %}">ГЛАВНАЯ</a></td>
    <td><a href="{% url 'authors_catalog' %}">КАТАЛОГ АВТОРОВ</a></td>
    <td><a href="{% url 'publishers_catalog' %}">КАТАЛОГ ИЗДАТЕЛЬСТВ</a></td>
    {% if user.is_authenticated %}
      <td>{{ user.username }}, <a href="{% url 'user_logout' %}">выход</a></td>
    {% else %}
      <td><a href="{% url 'user_login' %}">вход</a></td>
    {% endif %}
  </tr>
</table>

django/library/templates/publisher.html
{% extends 'books.html' %}


{% block title %}
  {{ pub|stringformat:"r" }}
{% endblock title %}


{% block heading %}
  {{ pub|stringformat:"r" }}
{% endblock heading %}


{% block extra_content %}
  <div>
    <hr>
  </div>
  <div>
    <form action="" method="post">
      {% csrf_token %}
      <input name="form" type="hidden" value="existing">
      
      <table cellpadding=5>
        {{ form1.as_table }}
      </table>
      
      <input type="submit" value="Добавить">
    </form>
  </div>
  <div>
    <hr>
  </div>
  <div>
    <form action="" method="post">
      {% csrf_token %}
      <input name="form" type="hidden" value="new">
      
      <table cellpadding=5>
        {{ form2.as_table }}
      </table>
      
      <input type="submit" value="Добавить">
    </form>
  </div>
{% endblock extra_content %}

django/library/templates/publishers.html
{% extends 'base.html' %}


{% block title %}
  Каталог издательств
{% endblock title %}


{% block content %}
  <div align="left">
    <table cellpadding=25>
      {% for pub in pubs %}
        <tr>
          <td>
            <a href="{% url 'publisher' pub.url %}">{{ pub|stringformat:"r" }}</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div>
    <hr>
  </div>
  <div>
    <form action="" method="post">
      {% csrf_token %}
      
      <table cellpadding=5>
        <tr>
          <th align="right">
            {{ form.name.label }}
          </th>
          <td>
            {{ form.name }}
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <input type="submit" value="Добавить">
          </td>
        </tr>
      </table>
    </form>
  </div>
{% endblock content %}

django/library/templates/register.html
{% extends 'base.html' %}


{% block title %}
  Регистрация пользователя
{% endblock title %}


{% block header %}
{% endblock header %}


{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    
    <table cellpadding=10>
      {{ form.as_table }}
      <tr>
        <td colspan=2 align="center">
          <input type="submit" value="Зарегистрировать">
        </td>
      </tr>
    </table>
    
  </form>
{% endblock content %}